### ISSUE TITLE
Face ImportError when running

### ISSUE THREAD

**Issue by Wilson-ZHANG** [presmerats/csn-project#1]
Hello,
I modified the code in train.py.
When dataset equals to 'cora','citeseer', or 'pubmed', it can run correctly.
However, when flags.DEFINE_string('dataset', 't1', 'Dataset string.') or flags.DEFINE_string('dataset', 'karate', 'Dataset string.'), I will get the traceback below.
Would you give me some advice to improve?
Thanks.

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data(FLAGS.dataset)
  File "/home/zhangqifan/projects/csn-project/src/gcn/gcn/gcn/utils.py", line 49, in load_data
    objects.append(pkl.load(f, encoding='latin1'))
ImportError: No module named 'numpy.core._multiarray_umath'

**Comment by Wilson-ZHANG** [comment]
Ok, I upgrade pip and pip install numpy to address this importerror~
